name: codeclimate
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
          node-version: '14'
    - run: npm ci
    - run: npm test
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '14'
    - run: npm ci
    - uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: 3528bf87af3ce1e5be6cc5256dacadeec8de17aa87b47b6525ac7dbdf9f0d8ec
      with:
        coverageCommand: npm run test:coverage
        debug: true